# vim:ft=yaml.ansible
---
ripgrep_version: 13.0.0
ripgrep_url: https://github.com/BurntSushi/ripgrep/releases/download/{{ ripgrep_version }}/ripgrep-{{ ripgrep_version }}-x86_64-unknown-linux-musl.tar.gz
ripgrep_extracted: /tmp/ripgrep-v{{ ripgrep_version }}/
ripgrep_folder: "{{ ripgrep_url | basename | splitext | first | splitext | first }}"
