# vim:ft=yaml.ansible
---
- name: Create directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: ug+rwx
  with_items:
    - /home/{{ ansible_user_id }}/.local/

- name: Download and extract archive
  ansible.builtin.unarchive:
    src: "{{ nodejs_url }}"
    remote_src: true
    dest: /home/{{ ansible_user_id }}/.local/
    extra_opts:
      - --strip-components=1
    exclude:
      - CHANGELOG.md
      - README.md
      - LICENSE
    creates: /home/{{ ansible_user_id }}/.local/bin/node

- name: Initialize npm prefix
  ansible.builtin.shell: PATH=~/.local/bin:$PATH npm set prefix '~/.local/'
  args:
    creates: /home/{{ ansible_user_id }}/.npmrc

- name: Patch ~/.bashrc
  ansible.builtin.lineinfile:
    path: /home/{{ ansible_user_id }}/.bashrc
    line: "{{ item }}"
  with_items:
    - export PATH=~/.local/bin:$PATH
